/*  */

DROP TABLE users;

CREATE TABLE users (
  id int NOT NULL UNIQUE AUTO_INCREMENT,
  name VARCHAR(20),
  PRIMARY KEY (id)
);

CREATE TABLE addresses (
  id int NOT NULL UNIQUE AUTO_INCREMENT,
  city VARCHAR(20) NOT NULL,
  street VARCHAR(255),
  user_id int,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

INSERT INTO users (name) VALUES ('Ivan');
INSERT INTO addresses (city,street,user_id) VALUES ('Kiev','peremogy',1);/*USE OWN ID GENERATED BY AUTO INCREMENT*/


SELECT * FROM users;